from __future__ import annotations

import re
from collections.abc import Mapping

# SQLcl echoes a feedback line for each statement it runs, which `sql -S` does
# not suppress. rest export output is written verbatim into files, so a stray
# echo landed at the top of every generated REST file, above the
# "-- Generated by ..." header, corrupting the artifact (ADT #149). db.py
# silences feedback around the injected DDL_LOCK_TIMEOUT at the source; this is
# the belt-and-braces backstop for whatever a user `config/STARTUP.sql` still
# emits after that restore.
#
# The set covers a statement, not just an ALTER SESSION: a STARTUP.sql that runs
# a `BEGIN DBMS_SESSION.SET_IDENTIFIER(...); END;` block, which is the shape the
# shipped STARTUP.sql template itself documents, echoes "PL/SQL procedure
# successfully completed." instead, and it went straight into line 1 of
# `__enable_schema.sql` on any run that did not happen to reach the connect
# preamble the cleanup trims. Seen live on CORE26 while closing `#313`. Literal
# strings rather than a pattern, so an echo can never be confused with a line of
# exported REST DDL.
_SQLCL_FEEDBACK_ECHOES = frozenset({
    "Session altered.",
    "PL/SQL procedure successfully completed.",
    "Commit complete.",
})


def _cleanup_sqlcl(output: str) -> list[str]:
    lines = output.splitlines()
    for index, line in enumerate(lines):
        if line.startswith("Connected."):
            lines = lines[index + 1:]
            break
    if len(lines) >= 2 and lines[-2].startswith("Disconnected") and lines[-1].startswith("Version"):
        lines = lines[:-2]
    return [line for line in lines if line.strip() not in _SQLCL_FEEDBACK_ECHOES]

# SQLcl releases the WHENEVER guard after the connect block, so errors raised by
# the request body keep their own semantics, which means a ``rest export;`` that
# failed still leaves SQLcl exiting 0. An empty module list is legitimate on its
# own (a schema may genuinely publish no REST services), but an empty list *plus*
# an Oracle/SQLcl diagnostic is a failed export that wrote no files and reported
# nothing (ADT #188).
_SQLCL_ERROR_PREFIXES = ("ORA-", "SP2-", "PLS-")


def _rest_export_error(lines: list[str]) -> str | None:
    """The first SQLcl/Oracle diagnostic in a REST export, if any."""
    for line in lines:
        if line.lstrip().startswith(_SQLCL_ERROR_PREFIXES):
            return line.strip()
    return None

# `ORDS.CREATE_ROLE` and `ORDS.DEFINE_PRIVILEGE` close a `rest export`, and both
# are schema-scoped: one privilege can name several modules, so it belongs to
# none of them. Splitting on `ORDS.DEFINE_MODULE` alone buried the whole trailer
# inside whichever module SQLcl emitted last, where the variables it assigns are
# not declared, so that module file no longer compiled (ADT #313).
_REST_TRAILER_CALLS = ("ORDS.CREATE_ROLE", "ORDS.DEFINE_PRIVILEGE")


def _split_rest_modules(lines: list[str]) -> tuple[list[str], list[list[str]], list[str]]:
    """Split a raw `rest export` into its preamble, module blocks and trailer.

    The export is one PL/SQL block: a preamble that opens it and enables the
    schema, one `ORDS.DEFINE_MODULE` run per published module, the schema-level
    roles and privileges, then a single `COMMIT;` and the block's own `END;`.
    The walk runs preamble to modules to trailer to done.

    It stops on the `COMMIT;` statement itself rather than on a lookahead to the
    line after it. The old terminator needed `END;` on the very next line, and a
    real export that carries a trailer puts a blank line between the two, so the
    test never fired and the split ran on to the end of the transcript.
    """
    preamble: list[str] = []
    modules: list[list[str]] = []
    trailer: list[str] = []
    current: list[str] = []
    state = "preamble"
    for line in lines:
        stripped = line.strip()
        if state == "done":
            continue
        if stripped == "COMMIT;":
            if current:
                modules.append(current)
                current = []
            state = "done"
            continue
        if "ORDS.DEFINE_MODULE" in line:
            if state == "modules" and current:
                modules.append(current)
            current = []
            state = "modules"
        elif state == "modules" and stripped.startswith(_REST_TRAILER_CALLS):
            if current:
                modules.append(current)
                current = []
            state = "trailer"
        if state == "preamble":
            preamble.append(line)
        elif state == "modules":
            current.append(line.rstrip())
        else:
            trailer.append(line.rstrip())
    if current:
        modules.append(current)
    return preamble, modules, trailer

def _rest_module_name(module: list[str]) -> str:
    text = "\n".join(module)
    match = re.search(r"p_module_name\s*=>\s*'([^']+)'", text)
    if not match:
        raise ValueError("Could not find ORDS module name in SQLcl REST export")
    return match.group(1)

def _schema_definition(preamble: list[str], trailer: list[str]) -> list[str]:
    """The schema-scoped half of the export: its preamble plus its trailer.

    The preamble is kept verbatim, opening declarations included. A schema that
    publishes a privilege exports a `DECLARE` section, and the old cleanup
    dropped the export's own `BEGIN` so a fresh one could be wrapped around the
    result, which put `DECLARE` inside a block that had already started: not
    ugly PL/SQL but invalid PL/SQL, rejected with ORA-06550 (ADT #313).

    Only the header date is rewritten, so re-exporting unchanged services is a
    no-op diff rather than a one-line churn.
    """
    content: list[str] = []
    for line in preamble:
        if line.startswith("-- Schema:"):
            line = line.split(" Date:")[0]
        content.append(line.rstrip())
    content.extend(trailer)
    return list(filter(None, content))

def _plsql_block(lines: list[str]) -> str:
    body = "\n".join(list(filter(None, lines)))
    return f"BEGIN\n{body}\nEND;\n/\n"

def _schema_block(lines: list[str]) -> str:
    """Close the export's own block instead of opening a second one."""
    body = "\n".join(lines)
    return f"{body}\nCOMMIT;\nEND;\n/\n"

# An unbounded SQLcl call is what "the REST export just keeps going" means: the
# child is left to sit for as long as it likes and the only visible sign is a
# crawling progress bar (Jan, 2026-08-07). One minute is the budget a REST
# export is expected to fit in; `rest_timeout_seconds` in the project config
# raises it for a schema that genuinely publishes more. Deliberately scoped to
# this one call, `patch -deploy` runs for minutes by design and must stay
# unbounded.
DEFAULT_REST_TIMEOUT_SECONDS = 60


def rest_timeout_seconds(config: Mapping[str, object]) -> int:
    """The REST export's SQLcl deadline, in seconds.

    A missing, non-numeric, or non-positive value falls back to the default
    rather than disabling the deadline: `rest_timeout_seconds: 0` reads as a
    mistake, and honouring it would restore the unbounded run this exists to
    end.
    """
    try:
        value = int(config.get("rest_timeout_seconds"))  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return DEFAULT_REST_TIMEOUT_SECONDS
    return value if value > 0 else DEFAULT_REST_TIMEOUT_SECONDS


def _rest_prefixes(config: Mapping[str, object]) -> list[str]:
    value = config.get("apex_rest_prefixes")
    if value is None:
        return [""]
    values = value if isinstance(value, list | tuple) else [value]
    return [str(item) for item in values]

def _matches_prefix(name: str, prefixes: list[str]) -> bool:
    return not prefixes or any(name.startswith(prefix) for prefix in prefixes)
