from __future__ import annotations

import re
from collections.abc import Mapping

# SQLcl echoes a feedback line for each ALTER SESSION it runs — "Session
# altered." — which `sql -S` does not suppress. rest export output is written
# verbatim into files, so a stray echo landed at the top of every generated REST
# file, above the "-- Generated by ..." header, corrupting the artifact (ADT
# #149). db.py silences feedback around the injected DDL_LOCK_TIMEOUT at the
# source; this is the belt-and-braces backstop for any feedback a user
# STARTUP.sql ALTER SESSION still emits after that restore.
_SQLCL_FEEDBACK_ECHOES = frozenset({"Session altered."})


def _cleanup_sqlcl(output: str) -> list[str]:
    lines = output.splitlines()
    for index, line in enumerate(lines):
        if line.startswith("Connected."):
            lines = lines[index + 1:]
            break
    if len(lines) >= 2 and lines[-2].startswith("Disconnected") and lines[-1].startswith("Version"):
        lines = lines[:-2]
    return [line for line in lines if line.strip() not in _SQLCL_FEEDBACK_ECHOES]

# SQLcl releases the WHENEVER guard after the connect block, so errors raised by
# the request body keep their own semantics — which means a ``rest export;`` that
# failed still leaves SQLcl exiting 0. An empty module list is legitimate on its
# own (a schema may genuinely publish no REST services), but an empty list *plus*
# an Oracle/SQLcl diagnostic is a failed export that wrote no files and reported
# nothing (ADT #188).
_SQLCL_ERROR_PREFIXES = ("ORA-", "SP2-", "PLS-")


def _rest_export_error(lines: list[str]) -> str | None:
    """The first SQLcl/Oracle diagnostic in a REST export, if any."""
    for line in lines:
        if line.lstrip().startswith(_SQLCL_ERROR_PREFIXES):
            return line.strip()
    return None

def _split_rest_modules(lines: list[str]) -> tuple[list[str], list[list[str]]]:
    first: list[str] = []
    modules: list[list[str]] = []
    current: list[str] = []
    append = False
    for index, line in enumerate(lines):
        module_started = "ORDS.DEFINE_MODULE" in line
        if not append and not module_started:
            first.append(line)
        if module_started:
            if current:
                modules.append(current)
            current = []
            append = True
        next_line_is_end = index + 1 < len(lines) and lines[index + 1].startswith("END;")
        if line.strip().startswith("COMMIT;") and next_line_is_end:
            append = False
        if append:
            current.append(line.rstrip())
    if current:
        modules.append(current)
    return first, modules

def _rest_module_name(module: list[str]) -> str:
    text = "\n".join(module)
    match = re.search(r"p_module_name\s*=>\s*'([^']+)'", text)
    if not match:
        raise ValueError("Could not find ORDS module name in SQLcl REST export")
    return match.group(1)

def _schema_definition(lines: list[str]) -> list[str]:
    content: list[str] = []
    for line in lines:
        if line.startswith("BEGIN"):
            continue
        if line.startswith("-- Schema:"):
            line = line.split(" Date:")[0]
        if line.startswith("END;"):
            break
        content.append(line.rstrip())
    return list(filter(None, content))

def _plsql_block(lines: list[str]) -> str:
    body = "\n".join(list(filter(None, lines)))
    return f"BEGIN\n{body}\nEND;\n/\n"

def _rest_prefixes(config: Mapping[str, object]) -> list[str]:
    value = config.get("apex_rest_prefixes")
    if value is None:
        return [""]
    values = value if isinstance(value, list | tuple) else [value]
    return [str(item) for item in values]

def _matches_prefix(name: str, prefixes: list[str]) -> bool:
    return not prefixes or any(name.startswith(prefix) for prefix in prefixes)
