"""Two exported `CREATE TABLE` versions, compared by Oracle (ADT #753).

`table_alter.py` answered this question in Python: parse both texts, key the
columns, compare the definition strings. It covered columns and nothing else, so
a PK, UNIQUE, FK, CHECK or index change produced an empty script, and a baseline
whose last column had lost its trailing comma silently absorbed the following
constraint clause and emitted a `MODIFY` for a column nobody touched.

Old ADT never had that class of defect because it never parsed anything: it
built the two versions as real tables in the connected schema and asked
`DBMS_METADATA_DIFF` what changed (`ADT--OLD/patch.py:2488`). Jan, settling
`#753`: *"The point was that I could trust that
DBMS_METADATA_DIFF.COMPARE_ALTER module more than any other solution."*

What lives here is everything around that call that is not SQL and not I/O: the
shadow names, and the rewrite that turns an exported file into DDL two copies of
one table can both run in one schema. The SQL is `queries/table_diff.py`; the
running of it is `table_diff_runner.py`.
"""

from __future__ import annotations

import re

from adt_ai.export_db.normalizers import sql_spans

#: The placeholder the rewrite plants and the runner substitutes. Old ADT's own
#: (`ADT--OLD/patch.py:2474`), kept because the two halves are written apart: the
#: rewrite does not know which side it is preparing, and the caller does.
SHADOW_MARKER = "$#"

#: The suffixes the two versions get. `$` is legal throughout an unquoted Oracle
#: identifier, and `%$1` / `%$2` is already what `shared/diff_tables.py` sweeps
#: and what `export_db` refuses to export, so a leftover from a run that died
#: with its connection is cleaned up by machinery that already exists.
SOURCE_MARKER = "$1"
TARGET_MARKER = "$2"

_CONSTRAINT_NAME_RE = re.compile(r"\bCONSTRAINT\s+(\S+)", flags=re.IGNORECASE)
_TABLE_NAME_RE = re.compile(r"\bTABLE\s+(\S+)", flags=re.IGNORECASE)
_IF_NOT_EXISTS_RE = re.compile(r"\s+IF\s+NOT\s+EXISTS\b", flags=re.IGNORECASE)
_IDENTITY_RE = re.compile(r"\s+GENERATED\s+BY\b.*$", flags=re.IGNORECASE)
_NOT_NULL_RE = re.compile(r"\bNOT\s+NULL\b", flags=re.IGNORECASE)


def shadow_table_names(table_name: str) -> tuple[str, str]:
    """The two names one schema holds while a table is being compared."""
    return f"{table_name}{SOURCE_MARKER}", f"{table_name}{TARGET_MARKER}"


def shadow_ddl(sql: str) -> str:
    """One exported table file, as DDL a shadow copy can be created from.

    Every step here is old ADT's (`get_table_for_diff`, `ADT--OLD/patch.py:2458`)
    and every one of them is load-bearing:

    * `IF NOT EXISTS` goes, because a shadow table that already exists is the
      state this run is trying not to be in and silence about it would compare
      the previous run's leftovers.
    * The text stops at the first statement terminator, so a file carrying a
      `COMMENT ON` or an `ALTER` after the `CREATE` does not run them twice.
    * `PARTITION BY` and everything after it goes: partitioning is suppressed on
      both sides of the comparison anyway (`queries/table_diff.py`), and building
      real partitions to describe a diff that ignores them is work for nothing.
    * An identity column's `GENERATED BY ...` goes, because two copies of it in
      one schema is two sequences, and the SXML carries the sequence's own name.
    * **The table name and every constraint name carry the marker**, which is the
      step the whole approach rests on: two copies of one table cannot share a
      constraint name, and the marker is what the comparison strips back out so
      Oracle sees one object rather than a rename of everything.

    Read through `sql_spans()` because a comment is not SQL: `-- see CONSTRAINT
    fk_x` is prose, and suffixing the word inside it corrupts the file for no
    reason. That rule is the project's since `#299` and the reason
    `table_alter.py` was rewritten twice.
    """
    body = _IF_NOT_EXISTS_RE.sub("", sql).split(";", 1)[0]
    body = re.split(r"\n\s*PARTITION\s+BY\b", body, maxsplit=1, flags=re.IGNORECASE)[0]
    return "\n".join(_shadow_line(line) for line in body.splitlines()).strip()


def _shadow_line(line: str) -> str:
    """One line of the rewrite, with its comments left exactly as written."""
    rendered = "".join(
        _shadow_code(line[start:end]) if kind == "code" else line[start:end]
        for kind, start, end in sql_spans(line)
    )
    return rendered.rstrip()


def _shadow_code(code: str) -> str:
    """Marker-suffix the names in a code span, and drop an identity clause.

    The identity rewrite keeps `NOT NULL` when the column had it, because
    `GENERATED ALWAYS AS IDENTITY` implies it and dropping the clause outright
    would make the shadow column nullable, which is a difference between the two
    copies that Oracle would then faithfully report as a change.
    """
    code = re.sub(r"\s+", " ", code)
    if _IDENTITY_RE.search(code):
        tail = " NOT NULL" if _NOT_NULL_RE.search(code) else ""
        trailing = "," if code.rstrip().endswith(",") else ""
        code = _IDENTITY_RE.sub("", code).rstrip().rstrip(",") + tail + trailing
    for pattern in (_CONSTRAINT_NAME_RE, _TABLE_NAME_RE):
        code = pattern.sub(_marked, code)
    return code


def _marked(match: re.Match[str]) -> str:
    """`CONSTRAINT x` / `TABLE x` with the marker appended to the name.

    The name is rebuilt from the match rather than replaced by substring, which
    is what `ADT--OLD` did (`line.replace(constraint, constraint + '$#')`) and
    what made it rewrite every other occurrence of the same word on the line,
    including the column list of the constraint it had just renamed.
    """
    name = match.group(1)
    quoted = len(name) > 1 and name.startswith('"') and name.endswith('"')
    marked = f'"{name[1:-1]}{SHADOW_MARKER}"' if quoted else f"{name}{SHADOW_MARKER}"
    return match.group(0)[: match.start(1) - match.start(0)] + marked


__all__ = [
    "SHADOW_MARKER",
    "SOURCE_MARKER",
    "TARGET_MARKER",
    "shadow_ddl",
    "shadow_table_names",
]
