"""The seven warning sections `patch -create` can close a schema block with.

Split out of `patch_create_render.py` when ADT #465 pushed that module past the
20 KB context guard (`tests/contracts/test_context_file_size.py`). The same call
`#285` made for `patch_preview_render.py` and `#417` for `print_patch_preview`: a
module that crosses the guard is split, never registered as debt.

The seam is the one `#451` already drew. That card turned every warning into a
section of its own on Jan's *"all warnings will have its own headers and list
below ... all underlined with dashes, not just warning"*, which made the warnings
a family with one shape and one printer, distinct from the report they hang off.
`patch_create_render.py` is left deciding what a build SAYS about the patch it
wrote; this file is what it says went wrong.

Nothing here connects, reads the repo, or writes a file: every function takes an
already-built report or result and turns it into rows.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

from adt_ai.cli.constants import print_adt_header
from adt_ai.patch.models import DatabasePatchResult, SchemaReport
from adt_ai.patch.object_folders import object_folder_resolver
from adt_ai.shared.file_list import nested_files, parent_folder, plain_row, print_file_rows
from adt_ai.shared.object_list import print_object_rows

# The seven warning sections `-create` can print, spelled once each. Constants
# rather than literals at the call sites so `tests/helpers/console_surface.py`
# records every one by name: it folds a module-level `NAME = "literal"` at the
# call site AND reads any `*_HEADER` constant on its own, which is what keeps a
# renamed warning a reviewed edit to the checked-in inventory (ADT #372).
#
# `WARNING - MISSING GRANTS:` was the eighth until ADT #501. It named a changed
# schema whose configured grant script resolved to nothing, which is a question
# only a run that injects grant scripts can ask; nothing is injected any more, so
# the section had nothing left to report.
OUTDATED_HEADER = "WARNING - OUTDATED FILES:"
UNCOMMITTED_HEADER = "WARNING - UNCOMMITTED FILES:"
NO_TABLE_BASELINE_HEADER = "WARNING - NO TABLE BASELINE:"
UNKNOWN_SCRIPTS_HEADER = "WARNING - UNKNOWN SCRIPTS:"
# Renamed from `WARNING - IGNORED SCRIPTS:` by ADT #509. The state leads and the
# consequence trails: `collect_patch_scripts` files a path here when the script
# is neither generated by this run nor carried by a selected commit, so NOT
# COMMITTED is the fact the reader can act on, by committing the script or
# widening the window, and IGNORED is only what ADT did about it. The constant
# keeps its name, and so does `PatchScripts.ignored`: the header is the surface
# Jan reads and the field is internal, so renaming both would double the blast
# radius for nothing.
IGNORED_SCRIPTS_HEADER = "WARNING - NOT COMMITTED SCRIPTS, IGNORED:"
# The two `#468` added, each a refusal that became a report. Jan spelled the
# first one himself, 2026-08-22: *"instead of listing this as patch failed you
# show a WARNING - OBJECTS CHANGED:"*.
CHANGED_OBJECTS_HEADER = "WARNING - OBJECTS CHANGED:"
NO_DATABASE_CLOCK_HEADER = "WARNING - NO DATABASE CLOCK:"

# The newer-commit rows sit inside the same 78-character budget the commit
# preview uses, rather than old ADT's flat `summary_len = 36`, a constant that
# still overflowed on a real project once the prefix was counted.
COMMIT_LINE_WIDTH = 78


def warning_rows(
    header: str,
    rows: list[str],
    *,
    nested: bool = False,
    folder_of: Callable[[str], str | None] = parent_folder,
    children: Callable[[str, int], list[str]] | None = None,
) -> None:
    """One warning section: the header, then a `  - ` list under it.

    The one printer for the six that list files or schema names, so the shape
    cannot drift between them the way `  -> ` did. `OBJECTS CHANGED:` is the
    exception and says so on itself: its rows are database objects, and since
    ADT #506 those go through `shared/object_list.py` in every section of the CLI
    that prints them. That arrow was unique to the warnings; `PATCH FILES:`,
    `ALTER STATEMENTS:` and `PROCESSED FILES:` have always printed `  - `, and
    Jan named the plain dash for the new section (ADT #451): *"a list of affected
    files with '-' not '->'"*. Consistency being the whole complaint, the five
    that already existed converge on it rather than the new one joining the odd
    shape. Since `#504` the rows themselves come from
    `shared/file_list.print_file_rows`, so the dash is shared with the other
    eleven sections rather than agreed with them.

    **`nested` defaults off because two of these sections do not list files.**
    `NO DATABASE CLOCK:` names schemas and `UNRESOLVED TABLES:` opens on a
    sentence: grouping either by a folder would invent a path where there is
    none. A section that does list paths passes the project's own answer in.
    `OBJECTS CHANGED:` was a third until ADT #506, and it did not stay flat, it
    left this printer: a listing of objects is its own shape, rendered by
    `shared/object_list.py` wherever the CLI prints one.

    No `lead_gap`, and no trailing blank either: these sit inside the schema
    loop, so the wider gap would open a hole in the middle of one schema's block.
    Jan: *"WARNING headers would probably have just 1 empty line above, since we
    are actually in a schema loop"*. That is what separates them from the object
    sections in `patch_create_render._print_object_changes`, which stand between
    whole blocks and do close themselves.
    """
    print_adt_header(header)
    print_file_rows(rows, nested=nested, folder_of=folder_of, children=children)


def print_uncommitted(report: SchemaReport, config: dict[str, Any]) -> None:
    """Files git reports dirty or untracked, per schema (ADT #276, narrowed #444)."""
    if not report.uncommitted:
        return
    warning_rows(
        UNCOMMITTED_HEADER,
        list(report.uncommitted),
        nested    = nested_files(config),
        folder_of = object_folder_resolver(config),
    )


def print_outdated(report: SchemaReport, config: dict[str, Any]) -> None:
    """The patch ships a version older than a commit that already exists (`#277`).

    Nothing else in the run names those commits: the preview table lists the ones
    that were SELECTED, so without this an outdated file reads exactly like a
    current one. `#451` moved it out of the file list and gave it a header,
    which is also what made room to say WHY each file is here rather than
    leaving a reader to decode a `^` and two dotted labels.

    The newer commits are listed newest first (patch.py:1636's
    `reversed(found_newer)`, preserved by `newer_commits`).

    The `N newer commits changed this file since <n>) <subject>` line `#451`
    wrote above them is gone (ADT `#456`), on Jan's *"in warn outdated files
    remove this line"*. The header already says the file is outdated and the
    rows under it already say by how many commits, so the sentence was the third
    telling; the commit being SHIPPED is on the `RELEVANT COMMITS:` table at the
    top of the same screen.
    """
    outdated = [item for item in report.files if item.newer and item.commit_number is not None]
    if not outdated:
        return
    newer = {item.path: item.newer for item in outdated}
    warning_rows(
        OUTDATED_HEADER,
        [item.path for item in outdated],
        nested    = nested_files(config),
        folder_of = object_folder_resolver(config),
        children  = lambda path, depth: [
            commit_line(number, summary, depth) for number, summary in newer[path]
        ],
    )


def print_unresolved_tables(result: DatabasePatchResult, config: dict[str, Any]) -> None:
    """A hash-mode table whose recorded version is out of reach (ADT #447).

    The baseline says which version the target holds, and the ALTER is generated
    by comparing that version against the one shipping. When the scanned history
    no longer carries the recorded content, there is nothing to compare, and the
    patch would otherwise ship a bare `CREATE TABLE` against a table that
    already exists. Naming the file is all ADT can do, the column change is the
    developer's to write into `patch_scripts/`.
    """
    if not result.unresolved_tables:
        return
    print_adt_header(NO_TABLE_BASELINE_HEADER)
    print("  the recorded version is not in the scanned history, so no ALTER was generated")
    print_file_rows(
        result.unresolved_tables,
        nested    = nested_files(config),
        folder_of = object_folder_resolver(config),
    )


def print_changed_objects(result: DatabasePatchResult) -> None:
    """Objects the database moved past after they were exported (ADT #261, #468).

    The patch ships the exported body for each of these, so deploying it reverts
    the live change. That was a refusal until Jan read one on his own screen,
    2026-08-22: *"it is a blocker, but I might not even be working with the files
    mentioned, so it is a stupid blocker ... it will be just a warning, not a
    show stopper"*.

    **The row is the type and the name, and nothing else**, which is his too:
    *"a simple list `  - <object_type> <object_name>` no stupid dates, nothing
    else; make it simple!"* The refusal used to carry each object's database
    timestamp, its export timestamp, its path and a `Run: adtai export_db`
    footer, four facts to read past before reaching the name. The command that
    fixes it is in `docs/patch.md`, said once, rather than under every list.

    **The one warning section that is not a `warning_rows` list** (ADT #506).
    Every other one lists files or schema names; this one lists OBJECTS, and Jan
    read it beside an `export_db` run on 2026-08-24: the same five objects, two
    shapes. So the rows come from `shared/object_list.py`, the renderer
    `EXPORTING <n> OBJECTS:` and `DELETED OBJECTS:` already print through, and
    only the header is shared with the warning family.
    """
    if not result.changed_objects:
        return
    print_adt_header(CHANGED_OBJECTS_HEADER)
    print_object_rows(
        (item.object_type, item.object_name) for item in result.changed_objects
    )


def print_no_database_clock(result: DatabasePatchResult) -> None:
    """Owners whose mirrored DDL times cannot be compared to a file at all.

    A mirror refreshed before ADT read the database's own UTC offset (`#394`)
    holds naive readings off a clock nothing recorded, so the check above cannot
    run for that owner. That is a weaker statement than a proven stale export and
    so cannot carry a harder consequence: it stopped the build until `#468` and
    reports beside the other one now. The fix is `adtai dependencies -refresh`,
    in `docs/patch.md` for the same reason.
    """
    if not result.unclocked_schemas:
        return
    warning_rows(NO_DATABASE_CLOCK_HEADER, list(result.unclocked_schemas))


def print_script_warnings(result: DatabasePatchResult, config: dict[str, Any]) -> None:
    """The two ways a per-patch script silently fails to ship (ADT #309).

    Old ADT printed both at the end of the run, unknown first (patch.py:1435-1440),
    and they are per-run rather than per-schema: the folder they name is scoped to
    the patch code, not to a schema.

    Neither is an error. `UNKNOWN` is a file in a slot no `patch_map` group can
    produce, so nothing would ever link it, almost always a typo in the folder
    name. `IGNORED` is a file in a real slot that no selected commit touched, which
    is normal on a shallow scan and a defect on a deep one. Saying nothing is
    what lets an author believe a script deployed when it never left the repo.
    """
    for header, paths in (
        (UNKNOWN_SCRIPTS_HEADER, result.scripts.unknown),
        (IGNORED_SCRIPTS_HEADER, result.scripts.ignored),
    ):
        if not paths:
            continue
        warning_rows(
            header,
            list(paths),
            nested    = nested_files(config),
            folder_of = object_folder_resolver(config),
        )


def commit_line(number: int, summary: str, depth: int) -> str:
    """A commit row hanging off a file: `    42) <subject>`, truncated to width.

    Same 78-character budget as the commit preview rather than old ADT's flat
    `summary_len = 36`, a constant that still overflowed once the prefix was
    counted (see `preview_rows_from`).

    **The indent is its parent's plus one, not a constant** (ADT #504). It was
    `"      - "` spelled here, six spaces, which is two levels below a file row
    sitting at two: Jan, 2026-08-24, *"they are indented with 6 spaces, that is
    wrong, I want just 4"*. The renderer passes the depth, so the row follows its
    file whether the list is flat or grouped under a folder, and the truncation
    is measured against the prefix that will actually be printed.

    **And it carries no dash** (ADT #507), which is the same indent through
    `plain_row` rather than `row_prefix`. Jan, reading a live `-create` later the
    same day: `      - 310) @Jan ...` becomes `      310) @Jan ...`. Every marked
    row under this header is a file the patch ships; a commit that already
    changed one is why the file is listed, not another entry in the list.
    """
    prefix = f"{plain_row('', depth)}{number}) "
    return prefix + summary[: max(COMMIT_LINE_WIDTH - len(prefix), 1)]


__all__ = [name for name in globals() if not name.startswith("__")]
