"""Code-coverage SQL for the ut module.

**Two Oracle APIs measure coverage, and they measure different things.**
``DBMS_PROFILER`` is line-level, "was this source line executed", keyed by
``plsql_profiler_data.line#``. ``DBMS_PLSQL_CODE_COVERAGE`` is basic-block level,
"was this single-entry single-exit block executed", keyed by
``dbmspcc_blocks.line`` **and** ``col``. One source line holds several blocks
and one block spans several lines, so the two row sets cannot agree and neither
is wrong. A report that compares a profiler line count to a block count is
comparing different units of measure.

**utPLSQL already runs both and pairs them**, on 12.2 and above, recording the
two ids against one logical run in ``ut_coverage_runs (coverage_run_id RAW,
line_coverage_id, block_coverage_id)``, the profiler runid beside the block
run_id. So this module does not start its own collection or reconcile the two
sources by hand: it calls ``ut_runner.coverage_start`` / ``coverage_stop`` and
reads the result through that mapping. Hand-rolling the combination would
reimplement, worse, something the framework does in the same session.

``coverage_start`` takes the run id as an **IN** parameter, which is what makes
this work through an ordinary statement gateway: the caller generates the RAW
and therefore always knows it, with no OUT bind and no read-back race.

Reachability, verified against the install rather than assumed: ``dbmspcc_units``
and ``dbmspcc_blocks`` have public synonyms; ``ut_coverage_runs`` has **no**
synonym but **is** granted SELECT to PUBLIC, so it is reached as
``ut3.ut_coverage_runs``. Everything else reads ``ALL_*`` scoped by an explicit
``:owner`` bind (never ``DBA_*``, never a dynamic performance view) matching
the contract in ``queries/suites.py``. ``ALL_*`` rather than ``USER_*`` because
``ut_owner`` made the schema a parameter and ``USER_*`` can only ever see the
connected one; the bind here is always the schema **under test**, never
``ut_owner``, since coverage measures the code and not the tests.
"""

from __future__ import annotations

# Open utPLSQL's coverage session. Starts the profiler and block coverage
# together; the id is ours, generated by the caller.
COVERAGE_START_STATEMENT = """
BEGIN
    ut_runner.coverage_start(a_coverage_run_id => HEXTORAW(:coverage_run_id));
END;
"""

# Close it. Separate from the read below: coverage rows are not complete until
# the session stops, so a caller that stopped and selected in one statement
# would race its own data.
COVERAGE_STOP_STATEMENT = """
BEGIN
    ut_runner.coverage_stop;
END;
"""

# Per-package block coverage for one utPLSQL coverage run.
#
# The join goes through `ut_coverage_runs` rather than guessing at the newest
# `dbmspcc` run: the RAW id is ours, so the mapping resolves exactly one block
# run and a concurrent coverage session elsewhere in the database cannot be
# mistaken for it.
#
# `not_feasible = 1` rows are EXCLUDED, and that is a deliberate disagreement
# with utPLSQL's own HTML percentage. A block marked through the COVERAGE pragma
# (NOT_FEASIBLE / NOT_FEASIBLE_START / NOT_FEASIBLE_END) is still written to
# dbmspcc_blocks with the flag set, Oracle flags it, it does not drop it, and
# subtracting it is the reporter's job. utPLSQL has an open defect that leaves
# pragma-excluded lines in its metrics, so a figure that honours the pragma
# reads higher than utPLSQL's. That is intended: the pragma exists precisely so
# an author can say "this block is not coverable", and a report that ignores it
# punishes them for saying so.
#
# COVERED is summed through a CASE rather than added directly. Oracle documents
# it as a flag, but a CASE is correct whether it is a flag or a hit count, and
# the difference would otherwise surface as a coverage percentage above 100.
#
# A LINES_COVERED aggregate sat beside them, the distinct `b.line` values
# carrying a covered block, feeding the `COVERED` column of the roll-up
# `-coverage` closed with. Card `#291` removed that table and nothing renders an
# executed-line count now, so the aggregate went with it rather than staying as a
# figure every run computes and no run prints.
PACKAGE_COVERAGE_QUERY = """
SELECT
    u.name                                                      AS package_name,
    COUNT(*)                                                    AS blocks_total,
    SUM(CASE WHEN b.covered > 0 THEN 1 ELSE 0 END)              AS blocks_covered
FROM ut3.ut_coverage_runs r
    JOIN dbmspcc_units u
        ON  u.run_id    = r.block_coverage_id
    JOIN dbmspcc_blocks b
        ON  b.run_id    = u.run_id
        AND b.object_id = u.object_id
WHERE 1 = 1
    AND r.coverage_run_id   = HEXTORAW(:coverage_run_id)
    AND u.owner             = :owner
    AND u.type              = 'PACKAGE BODY'
    AND b.not_feasible      = 0
GROUP BY u.name
ORDER BY u.name
"""

# The schema's packages with the size of each body, the half of the measurement
# coverage data cannot supply.
#
# Coverage rows only ever describe packages something executed, so a package a
# suite is supposed to test and never reached contributes no `dbmspcc` row at
# all. Its body still exists, and its line count is what lets `coverage_percent`
# scale a group by how much of it was measured: without this query an unreached
# target would simply vanish from the arithmetic and push the figure up.
#
# Test packages are excluded here, by the same `ut_pattern` that selects them in
# `queries/suites.py`, in SQL where the `NOT LIKE '%\\_UT'` used to be. Narrowing
# further (to the packages this run's suites actually test) happens in
# `ut3.coverage`, because the target set is a property of the run and a bind list
# built per run cannot be a stored constant the way every statement here is.
#
# LINES counts the **body**, and the body of the listed package, never its test
# partner's, and never the spec, since a count of declarations is not a measure
# of code. It is a scalar subquery rather than a join so a package with a spec
# and no body still gets its row, reading 0.
#
# `:owner` is the schema under test, never `ut_owner`. Coverage measures the
# code, and the two schemas are different questions.
#
# A MODULE_NAME column sat here until card `#291`, deriving `ut_module` group 1
# off the listed package so the removed coverage roll-up could group the whole
# schema by module. `SUMMARY PER MODULE:` groups the run's **suites**, whose module the
# discovery query already derives, so nothing reads a package's own module now.
SCHEMA_PACKAGES_QUERY = """
SELECT
    o.object_name,
    (
        SELECT COUNT(*)
        FROM all_source s
        WHERE 1 = 1
            AND s.owner         = o.owner
            AND s.name          = o.object_name
            AND s.type          = 'PACKAGE BODY'
    )                       AS lines
FROM all_objects o
WHERE 1 = 1
    AND o.owner             = :owner
    AND o.object_type       = 'PACKAGE'
    AND NOT REGEXP_LIKE(o.object_name, :ut_pattern, 'i')
ORDER BY o.object_name
"""

# A PACKAGE_COMPILE_SETTINGS_QUERY sat here until card `#291`. It read
# ALL_PLSQL_OBJECT_SETTINGS for `PLSQL_CODE_TYPE = NATIVE`, the one compile-time
# setting that explains an absent measurement, natively compiled code carries no
# PL/SQL instrumentation, so it produces no `dbmspcc_blocks` row and looked
# exactly like untested code. The `NATIVE` cell that named the cause went with
# the removed `-coverage` tables, leaving a query every run paid for and no
# surface rendered.
#
# If a reason for a blank `COVERAGE` cell is ever wanted back, that is the query
# to restore, and `PLSQL_OPTIMIZE_LEVEL` is not to be restored with it. It was
# selected alongside until 2026-08-06 to flag anything above level 1; measured on
# ICT_OWNER@ORCLPDB1, every one of the 78 package bodies is at level 2 (Oracle's
# default) and `dbmspcc_blocks` still recorded 36 of them, so the flag suppressed
# every real figure on every default database (card `#227`).

__all__ = [name for name in globals() if not name.startswith("__")]
