--
-- STARTUP.sample.sql -- template for the per-developer session-setup file.
--
-- Copy this file to config/STARTUP.sql and uncomment or add what you need;
-- the copy is gitignored, so personal session setup never dirties the repo.
-- Statements run once on every new database connection. Drop session setup
-- here (NLS settings, ALTER SESSION tuning, ...). The session identifier is
-- already set automatically from config/IDENTITY.yaml (db_schema) BEFORE this
-- file runs, so add your own DBMS_SESSION.SET_IDENTIFIER block only to
-- override it. A project-level config/STARTUP.sql overrides the repo-level
-- copy.
--
-- Mixed SQL*Plus / SQL / PL/SQL is supported, the same way SQLcl reads it:
--   * SQL*Plus directives (SET SERVEROUTPUT ON, SET DEFINE OFF, ...) are client
--     commands -- they are skipped on the python-oracledb path; SET SERVEROUTPUT
--     is emulated server-side. SQLcl deploys run the file verbatim.
--   * ALTER SESSION / SQL statements end with ';'.
--   * PL/SQL blocks (BEGIN ... END;) end with a lone '/' on its own line.
--
-- Example:
--
-- ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '. ';
-- ALTER SESSION SET NLS_DATE_FORMAT        = 'YYYY-MM-DD HH24:MI';
--
-- BEGIN
--     DBMS_APPLICATION_INFO.SET_CLIENT_INFO('ADT');
-- END;
-- /
