"""Code-coverage SQL for the ut3 module.

**Two Oracle APIs measure coverage, and they measure different things.**
``DBMS_PROFILER`` is line-level — "was this source line executed", keyed by
``plsql_profiler_data.line#``. ``DBMS_PLSQL_CODE_COVERAGE`` is basic-block level
— "was this single-entry single-exit block executed", keyed by
``dbmspcc_blocks.line`` **and** ``col``. One source line holds several blocks
and one block spans several lines, so the two row sets cannot agree and neither
is wrong. A report that compares a profiler line count to a block count is
comparing different units of measure.

**utPLSQL already runs both and pairs them**, on 12.2 and above, recording the
two ids against one logical run in ``ut_coverage_runs (coverage_run_id RAW,
line_coverage_id, block_coverage_id)`` — the profiler runid beside the block
run_id. So this module does not start its own collection or reconcile the two
sources by hand: it calls ``ut_runner.coverage_start`` / ``coverage_stop`` and
reads the result through that mapping. Hand-rolling the combination would
reimplement, worse, something the framework does in the same session.

``coverage_start`` takes the run id as an **IN** parameter, which is what makes
this work through an ordinary statement gateway: the caller generates the RAW
and therefore always knows it, with no OUT bind and no read-back race.

Reachability, verified against the install rather than assumed: ``dbmspcc_units``
and ``dbmspcc_blocks`` have public synonyms; ``ut_coverage_runs`` has **no**
synonym but **is** granted SELECT to PUBLIC, so it is reached as
``ut3.ut_coverage_runs``. Everything else reads ``USER_*`` — never ``DBA_*``,
never a dynamic performance view — matching the contract in ``queries/suites.py``.
"""

from __future__ import annotations

# Open utPLSQL's coverage session. Starts the profiler and block coverage
# together; the id is ours, generated by the caller.
COVERAGE_START_STATEMENT = """
BEGIN
    ut_runner.coverage_start(a_coverage_run_id => HEXTORAW(:coverage_run_id));
END;
"""

# Close it. Separate from the read below: coverage rows are not complete until
# the session stops, so a caller that stopped and selected in one statement
# would race its own data.
COVERAGE_STOP_STATEMENT = """
BEGIN
    ut_runner.coverage_stop;
END;
"""

# Per-package block coverage for one utPLSQL coverage run.
#
# The join goes through `ut_coverage_runs` rather than guessing at the newest
# `dbmspcc` run: the RAW id is ours, so the mapping resolves exactly one block
# run and a concurrent coverage session elsewhere in the database cannot be
# mistaken for it.
#
# `not_feasible = 1` rows are EXCLUDED, and that is a deliberate disagreement
# with utPLSQL's own HTML percentage. A block marked through the COVERAGE pragma
# (NOT_FEASIBLE / NOT_FEASIBLE_START / NOT_FEASIBLE_END) is still written to
# dbmspcc_blocks with the flag set — Oracle flags it, it does not drop it, and
# subtracting it is the reporter's job. utPLSQL has an open defect that leaves
# pragma-excluded lines in its metrics, so a figure that honours the pragma
# reads higher than utPLSQL's. That is intended: the pragma exists precisely so
# an author can say "this block is not coverable", and a report that ignores it
# punishes them for saying so.
#
# COVERED is summed through a CASE rather than added directly. Oracle documents
# it as a flag, but a CASE is correct whether it is a flag or a hit count, and
# the difference would otherwise surface as a coverage percentage above 100.
#
# LINES_COVERED is the **line** half of the same measurement, and it comes from
# this table rather than from DBMS_PROFILER. `dbmspcc_blocks` is keyed on `line`
# and `col`, so the block map already records which source line every block sits
# on; the distinct lines carrying a covered block are therefore a real
# executed-line count, out of rows this query has already joined. utPLSQL does
# pair a profiler run through `ut_coverage_runs.line_coverage_id`, and reading it
# would mean a second set of tables whose reachability nothing here has measured
# — exactly the assumption card #227 was written about. One source, already
# proven against a live schema.
#
# COUNT(DISTINCT), because several blocks share a source line: summing the block
# counts would report more covered lines than the package body has.
PACKAGE_COVERAGE_QUERY = """
SELECT
    u.name                                                      AS package_name,
    COUNT(*)                                                    AS blocks_total,
    SUM(CASE WHEN b.covered > 0 THEN 1 ELSE 0 END)              AS blocks_covered,
    COUNT(DISTINCT CASE WHEN b.covered > 0 THEN b.line END)     AS lines_covered
FROM ut3.ut_coverage_runs r
    JOIN dbmspcc_units u
        ON  u.run_id    = r.block_coverage_id
    JOIN dbmspcc_blocks b
        ON  b.run_id    = u.run_id
        AND b.object_id = u.object_id
WHERE 1 = 1
    AND r.coverage_run_id   = HEXTORAW(:coverage_run_id)
    AND u.owner             = :owner
    AND u.type              = 'PACKAGE BODY'
    AND b.not_feasible      = 0
GROUP BY u.name
ORDER BY u.name
"""

# Every package in the schema, so the report can list the ones no test touched —
# each with the size of its body.
#
# This is the half that makes the report worth printing. Coverage data can only
# ever describe packages that were executed; a package with no test contributes
# no coverage row at all and would silently vanish from a report built on
# coverage data alone — and that is the exact package the reader is looking for.
#
# `_UT` packages are excluded here rather than filtered downstream: they pair
# 1:1 with the packages under test, so listing them doubles the report and
# invites the reader to measure the coverage of the tests themselves. The suffix
# is the same selection contract `queries/suites.py` uses.
#
# LINES counts the **body**, and the body of the listed package — never its
# `_UT` partner's. It is what turns the uncovered list into a priority order
# rather than an alphabet: 900 uncovered lines and 9 uncovered lines are not the
# same problem, and the percentage above it says nothing about scale. The spec is
# excluded because a count of declarations is not a measure of code. It is a
# scalar subquery rather than a join so a package with a spec and no body still
# gets its row, reading 0.
SCHEMA_PACKAGES_QUERY = """
SELECT
    o.object_name,
    (
        SELECT COUNT(*)
        FROM user_source s
        WHERE 1 = 1
            AND s.name          = o.object_name
            AND s.type          = 'PACKAGE BODY'
    )                       AS lines
FROM user_objects o
WHERE 1 = 1
    AND o.object_type       = 'PACKAGE'
    AND o.object_name NOT LIKE '%\\_UT' ESCAPE '\\'
ORDER BY o.object_name
"""

# The one compile-time setting that explains an absent measurement.
#
# **It fails to zero, not to an error.** A natively compiled unit is machine code
# with the PL/SQL instrumentation stripped, so it produces no dbmspcc_blocks rows
# at all and the report would otherwise show it exactly like a package no test
# touched. Naming the cause is the entire value of the check.
#
# The setting is per-object and fixed at compile time — changing the session or
# system parameter does nothing until the unit is recompiled — so it comes from
# USER_PLSQL_OBJECT_SETTINGS per package body, never from the session-level
# parameter view, which would report an intention rather than what each body was
# actually compiled with.
#
# PLSQL_OPTIMIZE_LEVEL was selected here too until 2026-08-06, to flag anything
# above level 1. Measured on ICT_OWNER@ORCLPDB1: every one of the 78 package
# bodies is at level 2 — Oracle's default — and dbmspcc_blocks still recorded 36
# of them, ICT_COM_INVOICE at 22 of 25 blocks covered. The optimizer reshapes the
# line map DBMS_PROFILER reads, not the basic-block map this report is built on,
# so the flag suppressed every real figure on every default database and the
# section printed one repeated word. Do not reintroduce it.
PACKAGE_COMPILE_SETTINGS_QUERY = """
SELECT
    s.name                  AS package_name,
    s.plsql_code_type
FROM user_plsql_object_settings s
WHERE 1 = 1
    AND s.type              = 'PACKAGE BODY'
    AND s.name        NOT LIKE '%\\_UT' ESCAPE '\\'
ORDER BY s.name
"""

__all__ = [name for name in globals() if not name.startswith("__")]
