"""The one place a SQLcl session is opened (ADT #181).

ADT reaches Oracle two ways: python-oracledb, and SQLcl. ADT #179 gave the
first one a single construction point (``cli/gateways.build_gateway``, the only
``OracleGateway(...)`` in the tree) so that a change to what a connection does
reaches every command by inheritance rather than by editing eleven call sites.

The SQLcl half had no such point. ``OracleGateway.sqlcl_request`` composed one
connect block and ``diff/runner.py`` composed another, and the two had drifted:
only the first injected ``config/STARTUP.sql``. So ``adtai diff`` opened real
sessions against source *and* target with no session setup and no
``DBMS_SESSION.SET_IDENTIFIER``, the ADT #177 failure, still live, on any
schema whose DDL trigger requires a client identifier.

``sqlcl_connect`` is that missing point. It owns everything between "here is a
connection" and "the session is ready for my request": the connect line
(credentialed, wallet, or by stored name), the re-registration dance when a
saved credential has gone stale, the shared session settings, and the user's
``STARTUP.sql``. ``startup_sql`` is a **required** keyword, the ADT #177
omission was possible because ``OracleGateway`` defaulted it to ``None``, which
turned session setup into a per-call-site decision. Here it is a question the
caller has to answer.

``validate`` is the deliberate exception and needs none: it runs
``sql -S /nolog`` and never connects, so it has no connect line to build.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from zipfile import ZipFile

from adt_ai.shared.connections import DEFAULT_PORT, Connection
from adt_ai.shared.oracle_session import DDL_LOCK_TIMEOUT_STATEMENT
from adt_ai.shared.sqlcl_names import CONNMGR_DELETE_COMMAND, credential_fingerprint

# SQLcl prints "Session altered." (a FEEDBACK message, which ``sql -S`` does not
# suppress) for the DDL_LOCK_TIMEOUT ALTER SESSION injected into every payload.
# That output is captured verbatim into files by ``export_apex -rest``, so the
# stray line landed at the top of every generated REST file, above the
# "-- Generated by ..." header, corrupting the artifact (ADT #149). Silence
# feedback around our own injected setup and restore it before the user's
# STARTUP.sql runs, so a STARTUP.sql keeps whatever feedback level it sets.
SQLCL_SESSION_SETUP = f"SET FEEDBACK OFF\n{DDL_LOCK_TIMEOUT_STATEMENT};\nSET FEEDBACK ON"

# Substitution is disabled before anything else in the script, the connect line
# included (ADT #311). That line embeds the password verbatim
# (``connect USER/"pw"@service``), so a `&` in a credential reads as a
# substitution variable: SQLcl blocks prompting for a value on a stdin
# ``run_sqlcl_script`` points at DEVNULL, and the run hangs with no ORA code for
# ``WHENEVER SQLERROR`` to trap. ``SESSION_DEFAULT_DIRECTIVES`` carries the same
# directive, but ``#254``/``#283`` put it in the *deploy payload*, a different
# path, and one that only starts after the session is already open. So every
# SQLcl-driven command (``export_apex -rest``, ``validate``, ``diff``, and the
# deploy's own connect) was still exposed. Old ADT prefixed the whole request in
# ``lib/wrapper.py::sqlcl_request``; contributed as a fix in jkvetina/ADT#3.
SQLCL_DEFINE_OFF = "SET DEFINE OFF"

# Every connect is guarded, and that is the whole point (ADT #188). SQLcl's
# default is WHENEVER SQLERROR CONTINUE, so a script whose ``connect`` failed
# runs on regardless and its trailing ``exit;`` still returns 0, a dead session
# is indistinguishable from an empty result. ``export_apex -rest`` read that as
# "this schema has no REST services": no files, no message. Worse, on the
# registering path the gateway then recorded the SQLcl name and credential
# fingerprint back into the connection YAML for a store entry that had never
# been created, so the phantom survived every later run. That is the customer
# report this constant exists for, ``sqlcl``/``sqlcl_sync`` deleted by hand,
# written straight back by the next export, and still no connection.
#
# The guard is released again after the session setup, so errors from the user's
# STARTUP.sql and from the request body keep their own semantics.
SQLCL_CONNECT_GUARD = "WHENEVER SQLERROR EXIT FAILURE"
SQLCL_GUARD_RELEASE = "WHENEVER SQLERROR CONTINUE"


@dataclass(frozen=True)
class SqlclConnect:
    """One opened SQLcl session, ready for a request.

    ``name`` is what a later command in the same script refers to (``diff``
    names both sides in its ``DIFF -source ... -target ...`` line); it is
    ``None`` for a plain credentialed connect that was never saved.
    ``registers`` carries the connection whose ``sqlcl``/``sqlcl_sync``
    bookkeeping must be written back after the script has actually run.
    """

    lines     : tuple[str, ...]
    name      : str | None
    ephemeral : bool
    registers : Connection | None

    @property
    def script(self) -> str:
        return "\n".join(self.lines) + "\n"

    @property
    def by_name(self) -> bool:
        """True when this connected through SQLcl's store, carrying no credentials.

        The one failure mode that path has of its own: the store may not hold
        the name at all. Callers retry those with ``force_register=True``.
        """
        return self.name is not None and not self.ephemeral and self.registers is None


def sqlcl_connect(
    connection: Connection,
    *,
    startup_sql: str | None,
    project_root: Path | None = None,
    named_connections: bool = True,
    save_as: str | None = None,
    force_register: bool = False,
) -> SqlclConnect:
    """Build the block that opens ``connection`` in a generated SQLcl script.

    ``save_as`` is the alias to register an unnamed connection under for the
    duration of the script, ``diff`` needs one because SQLcl's ``DIFF`` command
    addresses its two sides by name. Left ``None``, an unnamed connection is
    opened with a plain credentialed ``connect`` and no cleanup, which is what
    every single-session caller wants.

    ``force_register`` re-saves a named connection whose fingerprint still
    matches. The SQLcl store does not travel with the project the way the
    connection YAML does, so a fresh fingerprint can still name an entry the
    local store has never seen; the caller retries once through this flag.
    """
    name = connection.sqlcl_name if named_connections else None

    if not name:
        if save_as is None:
            return _plan(_connect_line(connection, project_root), startup_sql)
        # Ad-hoc side of a multi-connection script: save under a throwaway
        # alias so the later command can address it, and drop it afterwards.
        return _plan(
            _connect_line(connection, project_root, save_name=save_as),
            startup_sql,
            name      = save_as,
            ephemeral = True,
        )

    if not force_register and connection.sqlcl_sync == credential_fingerprint(connection):
        # Connect by name only, no credentials in the script. A store that lost
        # the entry fails structurally and the caller re-registers.
        return _plan(
            f"connect -name {name}",
            startup_sql,
            name = name,
        )

    # ``CONNMGR DELETE`` stays *outside* the guard: dropping a name the store
    # never held is the normal first-run case, and aborting on it would make
    # registration impossible.
    return _plan(
        _connect_line(connection, project_root, save_name=name, savepwd=True),
        startup_sql,
        pre       = CONNMGR_DELETE_COMMAND.format(name=name),
        name      = name,
        registers = connection,
    )


def drop_command(name: str) -> str:
    """The cleanup line for an alias saved by ``save_as``."""
    return CONNMGR_DELETE_COMMAND.format(name=name)


def _plan(
    connect: str,
    startup_sql: str | None,
    *,
    pre: str | None = None,
    name: str | None = None,
    ephemeral: bool = False,
    registers: Connection | None = None,
) -> SqlclConnect:
    """Assemble one connect block: optional preamble, guarded connect, setup.

    The guard is unconditional, see ``SQLCL_CONNECT_GUARD``. ``pre`` is for
    lines that must run *before* it and are allowed to fail.
    """
    # SQLCL_DEFINE_OFF leads on every path, ahead of ``pre``: the CONNMGR DELETE
    # that ``pre`` carries is allowed to fail, but the connect behind it is the
    # line holding the credential.
    lines = [SQLCL_DEFINE_OFF] if pre is None else [SQLCL_DEFINE_OFF, pre]
    lines += [
        SQLCL_CONNECT_GUARD,
        connect,
        SQLCL_SESSION_SETUP,
        SQLCL_GUARD_RELEASE,
    ]
    if startup_sql:
        lines.append(startup_sql.rstrip())
    return SqlclConnect(
        lines     = tuple(lines),
        name      = name,
        ephemeral = ephemeral,
        registers = registers,
    )


def _connect_line(
    connection: Connection,
    project_root: Path | None,
    *,
    save_name: str | None = None,
    savepwd: bool = False,
) -> str:
    username = connection.username
    password = coerce_password(connection.password) or ""
    service  = connection.service or connection.sid or ""
    if save_name is None:
        save = ""
    elif savepwd:
        save = f"-save {save_name} -savepwd "
    else:
        save = f"-save {save_name} "
    if connection.wallet_path:
        wallet_path = _ensure_wallet_folder(
            resolve_wallet_path(connection.wallet_path, project_root)
        )
        wallet_zip = (
            wallet_path.with_suffix(".zip")
            if wallet_path.suffix != ".zip"
            else wallet_path
        )
        return f'connect {save}-cloudconfig "{wallet_zip}" {username}/"{password}"@{service}'
    if connection.hostname:
        dsn = f"{connection.hostname}:{connection.port or DEFAULT_PORT}/{service}"
    else:
        dsn = service
    return f'connect {save}{username}/"{password}"@{dsn}'


def coerce_password(password: str | bytes | None) -> str | None:
    """Decode a ``!!binary`` YAML password to text.

    A ``pwd: !!binary`` value reaches us as ``bytes``; embedding it in a connect
    string would write the literal ``b'secret'``.
    """
    if isinstance(password, bytes):
        return password.decode("utf-8")
    return password


def resolve_wallet_path(wallet_path: str, project_root: Path | None) -> Path:
    """Anchor a connection's wallet path to an absolute location for SQLcl.

    Wallet paths in connections.yaml are commonly stored relative to the project
    root (``config/Wallet_X.zip``). A generated SQLcl ``connect -cloudconfig`` line
    runs from a throwaway script under ``config/temp/`` with ``cwd`` set to the
    export target, so a relative wallet path resolves from neither the script's
    folder nor the cwd and SQLcl silently finds no wallet, ``export_apex -rest``
    then exports nothing (ADT #147). Anchor a relative path to the project root it
    is defined against, falling back to the process cwd when the root is unknown,
    so the connect line always carries an absolute wallet path. An already-absolute
    path is returned untouched.
    """
    path = Path(wallet_path).expanduser()
    if path.is_absolute():
        return path
    base = project_root if project_root is not None else Path.cwd()
    return base / path


def _ensure_wallet_folder(wallet_path: Path) -> Path:
    if wallet_path.suffix.lower() == ".zip":
        zip_path = wallet_path
        wallet_folder = wallet_path.with_suffix("")
    else:
        zip_path = wallet_path.with_suffix(".zip")
        wallet_folder = wallet_path
    if _wallet_needs_extract(wallet_folder) and zip_path.is_file():
        _extract_wallet_zip(zip_path, wallet_folder)
    return wallet_folder


def _wallet_needs_extract(wallet_folder: Path) -> bool:
    return not (wallet_folder / "tnsnames.ora").is_file()


def _extract_wallet_zip(zip_path: Path, wallet_folder: Path) -> None:
    wallet_folder.mkdir(parents=True, exist_ok=True)
    with ZipFile(zip_path) as archive:
        target = wallet_folder.resolve()
        for member in archive.infolist():
            member_path = (wallet_folder / member.filename).resolve()
            if target != member_path and target not in member_path.parents:
                raise RuntimeError(f"Unsafe wallet zip entry: {member.filename}")
        archive.extractall(wallet_folder)
